### ISSUE TITLE
Azure Data Studio Chocolatey version is outdated

### ISSUE THREAD

**Issue by jeansagi** [kendaleiv/chocolatey-azure-data-studio#12]
`choco search azure-data-studio` shows:
**azure-data-studio 1.48.0 [Approved] Downloads cached for licensed users**.

Version 1.48.1 was entirely omitted.
Right now, the current version is **1.49.0**.

Please support current versions (**1.49.0**) including future ones.

J.

**Comment by jeansagi** [comment]
Well, now version **1.49.1** is available...

**Comment by kendaleiv** [comment]
Thanks for letting me know!

https://community.chocolatey.org/packages/azure-data-studio/1.49.0 is failing verification testing.
https://community.chocolatey.org/packages/azure-data-studio/1.49.1 is approved.

**Comment by kendaleiv** [comment]
https://community.chocolatey.org/packages/azure-data-studio/1.49.0 is updated.

**Comment by jeansagi** [comment]
Perfect!
